server:
  port: 4003
spring:
  application:
    name: Data_Jpa_One_To_One
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/onetoone
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
